# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTesting < Formula
  desc ""
  homepage "https://github.com/MaxwelMazur/homebrew-tools"
  version "0.1.0-beta.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.19/goreleaser-testing_0.1.0-beta.19_Darwin_x86_64.tar.gz"
      sha256 "89621985886bc6b660334b930769f7bec985832a976cb3c2aab03f8736486d2a"

      def install
        bin.install "goreleaser-testing"
        bash_completion.install "completions/goreleaser-testing.bash" => "goreleaser-testing"
        zsh_completion.install "completions/goreleaser-testing.zsh" => "_azioncli"
        fish_completion.install "completions/goreleaser-testing.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.19/goreleaser-testing_0.1.0-beta.19_Darwin_arm64.tar.gz"
      sha256 "9185f8384025469593189d07981a6c4d4d8b5591c184323ace10d7d208b7695f"

      def install
        bin.install "goreleaser-testing"
        bash_completion.install "completions/goreleaser-testing.bash" => "goreleaser-testing"
        zsh_completion.install "completions/goreleaser-testing.zsh" => "_azioncli"
        fish_completion.install "completions/goreleaser-testing.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.19/goreleaser-testing_0.1.0-beta.19_Linux_arm64.tar.gz"
      sha256 "2ea842fdd91ed38ef874d21ff8a1a7be6cf1fe4be2be858662cac2c2e5d055bd"

      def install
        bin.install "goreleaser-testing"
        bash_completion.install "completions/goreleaser-testing.bash" => "goreleaser-testing"
        zsh_completion.install "completions/goreleaser-testing.zsh" => "_azioncli"
        fish_completion.install "completions/goreleaser-testing.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.19/goreleaser-testing_0.1.0-beta.19_Linux_x86_64.tar.gz"
      sha256 "446b405012b1f9ce585c830b50709486c3ecb54820ca743a2aa1c9047d0b6db9"

      def install
        bin.install "goreleaser-testing"
        bash_completion.install "completions/goreleaser-testing.bash" => "goreleaser-testing"
        zsh_completion.install "completions/goreleaser-testing.zsh" => "_azioncli"
        fish_completion.install "completions/goreleaser-testing.fish"
      end
    end
  end
end
