# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTesting < Formula
  desc ""
  homepage "https://github.com/MaxwelMazur/homebrew-tools"
  version "0.1.0-beta.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.1/goreleaser-testing_0.1.0-beta.1_Darwin_arm64.tar.gz"
      sha256 "4766d356fc980b15fe1ea9adb7acc8162efec4ca7522a62bbed42c72c58850f7"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.1/goreleaser-testing_0.1.0-beta.1_Darwin_x86_64.tar.gz"
      sha256 "1ac5fb8014f7409a59f32a0564c782d7a575f0bc20bd8bb79696dce5da183295"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.1/goreleaser-testing_0.1.0-beta.1_Linux_x86_64.tar.gz"
      sha256 "0f3999818c1e7aaad1161ed801dbf3b654a397f8604007bdc5243bb848082a16"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MaxwelMazur/goreleaser-testing/releases/download/v0.1.0-beta.1/goreleaser-testing_0.1.0-beta.1_Linux_arm64.tar.gz"
      sha256 "b905f4b4d38ef8f7f57eb96dd950ac7649eb897df05b742bce82603655da505b"

      def install
        bin.install "azioncli"
        bash_completion.install "completions/azioncli.bash" => "azioncli"
        zsh_completion.install "completions/azioncli.zsh" => "_azioncli"
        fish_completion.install "completions/azioncli.fish"
      end
    end
  end
end
